//
// Created by Marcel on 17-05-2026.
//

#ifndef ZX_BASIC_C_ERRORS_H
#define ZX_BASIC_C_ERRORS_H
#include <stddef.h>

typedef enum {
    ERR_0_OK = 0,
    ERR_1_NEXT_WITHOUT_FOR,
    ERR_2_VARIABLE_NOT_FOUND,
    ERR_3_SUBSCRIPT_WRONG,
    ERR_4_OUT_OF_MEMORY,
    ERR_5_OUT_OF_SCREEN,
    ERR_6_NUMBER_TOO_BIG,
    ERR_7_NO_GOSUB,
    ERR_8_END_FILE,
    ERR_9_STOP,
    ERR_A_INVALID_ARGUMENT,
    ERR_B_INTEGER_OUT_OF_RANGE,
    ERR_C_NONSENS_IN_BASIC,
    ERR_D_BREAK,
    ERR_E_OUT_OF_DATA,
    ERR_F_INVALID_FILENAME,
    ERR_G_NO_ROOM_FOR_LINE,
    ERR_H_STOP_IN_INPUT,
    ERR_I_NO_NEXT,
    ERR_J_INVALID_IO,
    ERR_K_INVALID_COLOUR,
    ERR_L_BREAK_INTO_PROGRAM,
    ERR_M_RAMTOP_NO_GOOD,
    ERR_N_STATEMENT_LOST,
    ERR_O_INVALID_STREAM,
    ERR_P_FN_WITHOUT_DEF,
    ERR_Q_PARAMETER_ERROR,
    ERR_R_TAPE_LOADING,
    ERR_NOT_YET_IMPLEMENTED,
    ERR_UNKNOWN,
} ZxError;

void error_message(ZxError error, char *message, size_t message_size);
const char *get_zx_error_message(ZxError error);

#endif //ZX_BASIC_C_ERRORS_H
